### ISSUE TITLE
'invalid data' error on Windows on 0.12.7

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/exec-file-sync#3]
from https://github.com/sindresorhus/win-release/pull/3#discussion_r38011013:

```
> require('exec-file-sync')('ver.exe')
TypeError: invalid data
    at WriteStream.Socket.write (net.js:633:11)
    at execFileSync (child_process.js:1364:20)
    at repl:1:26
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
```

**Comment by sindresorhus** [comment]
On Node.js 0.12.7 it uses the native `child_process.execFileSync`, so this should probably be a Node.js issue instead.

Proof:

```
> require('child_process').execFileSync('ver.exe')
TypeError: invalid data
    at WriteStream.Socket.write (net.js:633:11)
    at Object.execFileSync (child_process.js:1364:20)
    at repl:1:26
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
```

**Comment by silverwind** [comment]
Works in io.js 3.1.0 at least.

**Comment by silverwind** [comment]
Been looking through io.js's commit history, couldn't find any specific commit fixing that error. Closest I could find is https://github.com/nodejs/node/commit/785481149d59fddead9007d469e2578204f24cfb.

Maybe it's best to use the fallback on 0.12.x too, as it's unlikely that branch will receive a fix if we can't exactly identify what to backport.

**Comment by sindresorhus** [comment]
This package is now deprecated.
